/root/collaborative-stegosystem/collaborative-stegosystem/src/environment.py:21: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])




Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:21<00:00,  5.41s/it]
WARNING:root:The `device_map` argument is not provided. We will override the device_map argument. to set the entire model on the current device. If you want to set the model on multiple devices, please provide a custom `device_map` argument.



Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:20<00:00,  5.13s/it]
WARNING:root:The `device_map` argument is not provided. We will override the device_map argument. to set the entire model on the current device. If you want to set the model on multiple devices, please provide a custom `device_map` argument.



Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:21<00:00,  5.40s/it]
WARNING:root:The `device_map` argument is not provided. We will override the device_map argument. to set the entire model on the current device. If you want to set the model on multiple devices, please provide a custom `device_map` argument.
WARNING:accelerate.utils.other:Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Training Progress:   0%|                                                                                                     | 0/10 [00:00<?, ?it/s]
An error occurred during training: respond_to_batch() got an unexpected keyword argument 'max_length'