Traceback (most recent call last):
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/main.py", line 15, in <module>
    main(args.config)
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/main.py", line 8, in main
    experiment.run()
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/src/experiment.py", line 32, in run
    self.trainer.train(self.config['num_episodes'])
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/src/trainers/ppo_trainer.py", line 64, in train
    alice_action, alice_log_prob, alice_value = self.alice.act(state_tensor)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/src/agents/alice.py", line 8, in act
    return action, action_probs[action].item(), value.item()
                   ~~~~~~~~~~~~^^^^^^^^
IndexError: index 39 is out of bounds for dimension 0 with size 1